---
tytul: "Opieka Koordynowana w POZ"
podtytul: "Nowoczesny model opieki nad pacjentem z chorobami przewlekłymi - kompleksowa diagnostyka, leczenie i koordynacja przez Twojego lekarza rodzinnego."
opis_glowny: "Opieka koordynowana to model w którym lekarz POZ koordynuje cały proces leczenia. Edytuj treść w panelu CMS."
zakres1_tytul: "Kardiologia"
zakres1_opis: "Diagnostyka i leczenie chorób układu krążenia - nadciśnienie, niewydolność serca, arytmie."
zakres2_tytul: "Diabetologia"
zakres2_opis: "Kompleksowa opieka nad pacjentami z cukrzycą - edukacja, monitoring, leczenie."
zakres3_tytul: "Endokrynologia (choroby tarczycy)"
zakres3_opis: "Diagnostyka i leczenie chorób tarczycy - niedoczynność, nadczynność, guzki."
zakres4_tytul: "Pulmonologia"
zakres4_opis: "Opieka nad pacjentami z astmą, POChP i innymi chorobami układu oddechowego."
korzysc1: "Szybszy dostęp do badań specjalistycznych - bez długiego oczekiwania"
korzysc2: "Indywidualny Plan Opieki Medycznej (IPOM) - dostosowany do Twoich potrzeb"
korzysc3: "Koordynator opieki - jedna osoba prowadząca Twoje leczenie"
korzysc4: "Konsultacje specjalistów bez wychodzenia z placówki POZ"
korzysc5: "Edukacja zdrowotna - programy zmiany stylu życia"
korzysc6: "Lepsze rezultaty leczenia dzięki spójnemu podejściu"
---
